config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pictures

  root "pictures#index"

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, styles: { :medium => "800x800#", :thumb => "250x250#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :find_picture, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[:index,:show]
  def index
    @picture = Picture.all
  end

  def show
    
  end

  def new
    @picture = current_user.pictures.build
  end

  def create
    @picture = current_user.pictures.build(picture_params)

    if @picture.save
      redirect_to @picture, notice: "Successfully added new picture"
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update
    if @picture.update(picture_params)
      redirect_to @picture
    else
      render 'edit'
    end
  end

  def destroy
    @picture.destroy
    redirect_to root_path, notci: "Successfully deleted the picture"
  end

  private

  def find_picture
    @picture = Picture.find(params[:id])
  end

  def picture_params
    params.require(:picture).permit(:title,:description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="large-12 navbar-main">
          <div class="medium-4 columns">
            <div class="left" style="padding-top: 0.5rem">
              <%= link_to "Location Ile de Ré", root_path %>
            </div>
          </div>
          <% if user_signed_in? %>
          <div class="medium-8 columns right" style="padding-top: 0.35rem;">
            <div class="text-right">
              <%= link_to "Add Picture", new_picture_path, class: 'button radius tiny user_action' %>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'button radius tiny user_action' %>
            </div>
          </div>
          <% else %>
            <div class="medium-8 columns right" style="padding-top: 0.35rem">
              <div class="text-right">
                <%= link_to "Admin", new_user_session_path, class: 'button radius tiny user_action' %>
              </div>
            </div>
          <% end %>
    </div>
    <div>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "alert" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= simple_form_for @picture, html: { multipart: true } do |p| %>
  <% if @picture.errors.any? %>
    <div id="errors">
      <p>@picture.errors.count Prevented this picture from saving</p> 
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li>msg</li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="row">
      
      <div class="small-6 columns">
        <div class="row">
          <div class="small-8 columns"> 
            <%= p.input :title, input_html: { class:"input" } %>
            <%= p.input :description, input_html: { class:"input" } %></div>
            <%= p.input :image %>
          </div>
        </div>
      </div>

      <div class="small-6">
        <div class="row">
            <div class="small-6 small-offset-4 columns">
              <br>
              <%= p.button :submit, class:"button success radius small" %>
            </div>
        </div>
      </div>
      
    </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Edit picture</h1>

<%= render 'form' %>

app/views/pictures/index.html.erb
<br>
<% @picture.each_slice(3) do |pictures| %>
  <div class="row">
    <% pictures.each do |picture| %>
      <div class="large-4 columns">
        <div class="picture">
          <div class="image_wrapper">
            <%= link_to picture do %>
              <%= image_tag picture.image.url(:thumb) %>
              <h2> <%= link_to picture.title, picture %></h2>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form' %>

<br>

<%= link_to "Back", root_path, class: "button secondary radius tiny" %>

app/views/pictures/show.html.erb
<div class="main-content">
  <div class="medium-4 columns">
    <%= image_tag @picture.image.url(:medium, class:"picture-image") %>
  </div>
  <div class="medium-8 columns">
    <h1> <%= @picture.title %></h1>
    <p><%= @picture.description %></p>
    <p>Submitted by <%= @picture.user.email %></p>
    <% if user_signed_in? %>
      <p>
        <%= link_to "Back", root_path, class: "button secondary radius tiny" %>
        <%= link_to "Edit", edit_picture_path, class: "button radius tiny" %>
        <%= link_to "Delete", picture_path, method: :delete,data: { confirm: "Are you sure ?"}, class: "button radius tiny" %>
      </p>
    <% end %>
  </div>
</div>